#!/bin/bash

TAG=hackthe6ix/landing-2021:latest
NAME=owo

function dev() {
    docker build --target development -t $TAG .;
    docker run --name $NAME \
        -v ${PWD}/static:/usr/var/app/static \
        -v ${PWD}/src:/usr/var/app/src \
        -p 8080:8080 \
        -it $TAG;
    echo "" && docker rm $NAME;
}

function debug() {
    docker exec -it $NAME /bin/sh;
}

function prod() {
    docker build --target production -t $TAG .;
    docker run \
        -v ${PWD}/dist:/usr/var/app/dist \
        -it $TAG;
}

eval "$@ && exit 0";